name: CI # Name of the Action

on: [push] # When this action runs on ex: push or pull request

jobs:
  build:

    runs-on: ubuntu-latest # Which OS this runs on, you can also build on Windows or MacOS
    strategy:
      matrix:
        python-version: [3.8] # You can build against multiple Python versions

    steps:
    - uses: actions/checkout@v2 # Calling a pre-built GitHub Action which allows your Action to access your repository
    - name: Set up Python ${{ matrix.python-version }} # Name of an action that sets up Python
      uses: actions/setup-python@v2 # A pre-built GitHub Action that sets up a Python environment
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # If we have a requirements.txt, then install it
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        role-duration-seconds: 500
        role-session-name: Github_Action
    - name: DVC install
      uses: iterative/setup-dvc@v1
    - name: DVC pull
      run: |
        dvc pull 
    - name: Test with pytest # Final action which runs pytest. If any test fails, then this Action fails
      run: |
        pytest src/tests -vv
